version: 2
jobs:
  one:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run: echo "A first hello"
  two:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run: npm test
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two